;; Native-feeling LFE facade for the stable plain-term Wiregrid ABI.
(defmodule wiregrid
  (export all))

;; Instance/session lifecycle.
(defun version () (wiregrid_api:version))
(defun protocol-version () (wiregrid_api:protocol_version))
(defun foreign-protocol-version () (wiregrid_api:foreign_protocol_version))
(defun c-abi-major () (wiregrid_api:c_abi_major))
(defun capabilities (name) (wiregrid_api:capabilities name))
(defun describe (name) (wiregrid_api:describe name))

;; Closed constructors from the stable plain-term ABI. Keeping these here makes
;; the ordinary LFE façade complete; applications can opt into wiregrid_macros
;; for compile-time specialization rather than needing macros for basic terms.
(defun topic-user (id) (wiregrid_api:topic_user id))
(defun topic-channel (id) (wiregrid_api:topic_channel id))
(defun topic-thread (id) (wiregrid_api:topic_thread id))
(defun topic-room (id) (wiregrid_api:topic_room id))
(defun topic-game (id) (wiregrid_api:topic_game id))
(defun topic-document (id) (wiregrid_api:topic_document id))
(defun topic-custom (namespace value) (wiregrid_api:topic_custom namespace value))
(defun target-topic (topic) (wiregrid_api:target_topic topic))
(defun target-room (room) (wiregrid_api:target_room room))
(defun target-user (user) (wiregrid_api:target_user user))
(defun target-session (session) (wiregrid_api:target_session session))
(defun presence-status (status) (wiregrid_api:presence_status status))
(defun presence-custom (status) (wiregrid_api:presence_custom status))
(defun signal-kind (kind) (wiregrid_api:signal_kind kind))

(defun start-instance (name) (wiregrid_api:start_instance name))
(defun start-instance (name opts) (wiregrid_api:start_instance name opts))
(defun stop-instance (name) (wiregrid_api:stop_instance name))
(defun instance-child-spec (name) (wiregrid_api:instance_child_spec name))
(defun instance-child-spec (name opts) (wiregrid_api:instance_child_spec name opts))
(defun connect (name user pid) (wiregrid_api:connect name user pid))
(defun connect (name user pid opts) (wiregrid_api:connect name user pid opts))
(defun connect-resumable (name user pid) (wiregrid_api:connect_resumable name user pid))
(defun connect-resumable (name user pid opts) (wiregrid_api:connect_resumable name user pid opts))
(defun resume-session (name user pid token) (wiregrid_api:resume_session name user pid token))
(defun resume-session (name user pid token opts) (wiregrid_api:resume_session name user pid token opts))
(defun disconnect (name session) (wiregrid_api:disconnect name session))
(defun disconnect (name session reason) (wiregrid_api:disconnect name session reason))
(defun disconnect-user (name user) (wiregrid_api:disconnect_user name user))
(defun disconnect-user (name user reason) (wiregrid_api:disconnect_user name user reason))
(defun set-session-metadata (name session metadata) (wiregrid_api:set_session_metadata name session metadata))

;; Subscriptions and fanout.
(defun subscribe (name session topic) (wiregrid_api:subscribe name session topic))
(defun subscribe (name session topic context) (wiregrid_api:subscribe name session topic context))
(defun unsubscribe (name session topic) (wiregrid_api:unsubscribe name session topic))
(defun subscribe-many (name session topics) (wiregrid_api:subscribe_many name session topics))
(defun subscribe-many (name session topics context) (wiregrid_api:subscribe_many name session topics context))
(defun unsubscribe-many (name session topics) (wiregrid_api:unsubscribe_many name session topics))
(defun sync-subscriptions (name session topics) (wiregrid_api:sync_subscriptions name session topics))
(defun sync-subscriptions (name session topics context) (wiregrid_api:sync_subscriptions name session topics context))
(defun sync-topology (name session topology) (wiregrid_api:sync_topology name session topology))
(defun sync-topology (name session topology opts) (wiregrid_api:sync_topology name session topology opts))
(defun publish (name topic event) (wiregrid_api:publish name topic event))
(defun publish (name topic event opts) (wiregrid_api:publish name topic event opts))
(defun prepare (name event) (wiregrid_api:prepare name event))
(defun publish-prepared (name topic prepared) (wiregrid_api:publish_prepared name topic prepared))
(defun publish-prepared (name topic prepared opts) (wiregrid_api:publish_prepared name topic prepared opts))
(defun publish-batch (name topic events) (wiregrid_api:publish_batch name topic events))
(defun publish-batch (name topic events opts) (wiregrid_api:publish_batch name topic events opts))
(defun publish-topics (name topics event) (wiregrid_api:publish_topics name topics event))
(defun publish-topics (name topics event opts) (wiregrid_api:publish_topics name topics event opts))
(defun publish-topics-prepared (name topics prepared) (wiregrid_api:publish_topics_prepared name topics prepared))
(defun publish-topics-prepared (name topics prepared opts) (wiregrid_api:publish_topics_prepared name topics prepared opts))
(defun publish-room (name room event) (wiregrid_api:publish_room name room event))
(defun publish-room (name room event opts) (wiregrid_api:publish_room name room event opts))
(defun publish-room-prepared (name room prepared) (wiregrid_api:publish_room_prepared name room prepared))
(defun publish-room-prepared (name room prepared opts) (wiregrid_api:publish_room_prepared name room prepared opts))
(defun publish-rooms (name rooms event) (wiregrid_api:publish_rooms name rooms event))
(defun publish-rooms (name rooms event opts) (wiregrid_api:publish_rooms name rooms event opts))
(defun publish-rooms-prepared (name rooms prepared) (wiregrid_api:publish_rooms_prepared name rooms prepared))
(defun publish-rooms-prepared (name rooms prepared opts) (wiregrid_api:publish_rooms_prepared name rooms prepared opts))
(defun send-user (name user event) (wiregrid_api:send_user name user event))
(defun send-user (name user event opts) (wiregrid_api:send_user name user event opts))
(defun send-user-prepared (name user prepared) (wiregrid_api:send_user_prepared name user prepared))
(defun send-user-prepared (name user prepared opts) (wiregrid_api:send_user_prepared name user prepared opts))
(defun send-users (name users event) (wiregrid_api:send_users name users event))
(defun send-users (name users event opts) (wiregrid_api:send_users name users event opts))
(defun send-users-prepared (name users prepared) (wiregrid_api:send_users_prepared name users prepared))
(defun send-users-prepared (name users prepared opts) (wiregrid_api:send_users_prepared name users prepared opts))
(defun dispatch (name targets event) (wiregrid_api:dispatch name targets event))
(defun dispatch (name targets event opts) (wiregrid_api:dispatch name targets event opts))
(defun dispatch-prepared (name targets prepared) (wiregrid_api:dispatch_prepared name targets prepared))
(defun dispatch-prepared (name targets prepared opts) (wiregrid_api:dispatch_prepared name targets prepared opts))
(defun compile-dispatch (name targets) (wiregrid_api:compile_dispatch name targets))
(defun dispatch-plan (name plan event) (wiregrid_api:dispatch_plan name plan event))
(defun dispatch-plan (name plan event opts) (wiregrid_api:dispatch_plan name plan event opts))
(defun dispatch-plan-prepared (name plan prepared) (wiregrid_api:dispatch_plan_prepared name plan prepared))
(defun dispatch-plan-prepared (name plan prepared opts) (wiregrid_api:dispatch_plan_prepared name plan prepared opts))
(defun send-session (name session event) (wiregrid_api:send_session name session event))
(defun send-session (name session event opts) (wiregrid_api:send_session name session event opts))
(defun send-session-prepared (name session prepared) (wiregrid_api:send_session_prepared name session prepared))
(defun send-session-prepared (name session prepared opts) (wiregrid_api:send_session_prepared name session prepared opts))
(defun send-sessions (name sessions event) (wiregrid_api:send_sessions name sessions event))
(defun send-sessions (name sessions event opts) (wiregrid_api:send_sessions name sessions event opts))
(defun send-sessions-prepared (name sessions prepared) (wiregrid_api:send_sessions_prepared name sessions prepared))
(defun send-sessions-prepared (name sessions prepared opts) (wiregrid_api:send_sessions_prepared name sessions prepared opts))
(defun ack (name session) (wiregrid_api:ack name session))
(defun ack (name session delivery-id) (wiregrid_api:ack name session delivery-id))
(defun ack-many (name session delivery-ids) (wiregrid_api:ack_many name session delivery-ids))
(defun pending (name session) (wiregrid_api:pending name session))
(defun decode-payload (name payload) (wiregrid_api:decode_payload name payload))

;; Presence.
(defun presence (name user) (wiregrid_api:presence name user))
(defun set-presence (name session status) (wiregrid_api:set_presence name session status))
(defun set-presence (name session status metadata) (wiregrid_api:set_presence name session status metadata))
(defun watch-presence (name session user) (wiregrid_api:watch_presence name session user))
(defun watch-presence (name session user context) (wiregrid_api:watch_presence name session user context))
(defun unwatch-presence (name session user) (wiregrid_api:unwatch_presence name session user))
(defun watch-presence-many (name session users) (wiregrid_api:watch_presence_many name session users))
(defun watch-presence-many (name session users context) (wiregrid_api:watch_presence_many name session users context))
(defun unwatch-presence-many (name session users) (wiregrid_api:unwatch_presence_many name session users))
(defun sync-presence-watches (name session users) (wiregrid_api:sync_presence_watches name session users))
(defun sync-presence-watches (name session users context) (wiregrid_api:sync_presence_watches name session users context))

;; Rooms and signaling.
(defun join-room (name room session) (wiregrid_api:join_room name room session))
(defun join-room (name room session opts) (wiregrid_api:join_room name room session opts))
(defun leave-room (name room session) (wiregrid_api:leave_room name room session))
(defun join-rooms (name rooms session) (wiregrid_api:join_rooms name rooms session))
(defun join-rooms (name rooms session opts) (wiregrid_api:join_rooms name rooms session opts))
(defun leave-rooms (name rooms session) (wiregrid_api:leave_rooms name rooms session))
(defun sync-rooms (name session rooms) (wiregrid_api:sync_rooms name session rooms))
(defun sync-rooms (name session rooms opts) (wiregrid_api:sync_rooms name session rooms opts))
(defun resume-room (name room old-session new-session) (wiregrid_api:resume_room name room old-session new-session))
(defun room-members (name room) (wiregrid_api:room_members name room))
(defun room-members (name room limit) (wiregrid_api:room_members name room limit))
(defun room-metadata (name room) (wiregrid_api:room_metadata name room))
(defun set-room-metadata (name room session metadata) (wiregrid_api:set_room_metadata name room session metadata))
(defun set-room-metadata (name room session metadata opts) (wiregrid_api:set_room_metadata name room session metadata opts))
(defun set-room-ttl (name room session ttl-ms) (wiregrid_api:set_room_ttl name room session ttl-ms))
(defun signal (name room session kind payload) (wiregrid_api:signal name room session kind payload))
(defun signal (name room session kind payload opts) (wiregrid_api:signal name room session kind payload opts))

;; Ephemeral activity and receipts.
(defun activity (name session topic kind value) (wiregrid_api:activity name session topic kind value))
(defun activity (name session topic kind value opts) (wiregrid_api:activity name session topic kind value opts))
(defun activities (name topic kind) (wiregrid_api:activities name topic kind))
(defun activities (name topic kind limit) (wiregrid_api:activities name topic kind limit))
(defun typing (name session topic) (wiregrid_api:typing name session topic))
(defun typing (name session topic opts) (wiregrid_api:typing name session topic opts))
(defun receipt (name session value) (wiregrid_api:receipt name session value))
(defun receipt (name session value opts) (wiregrid_api:receipt name session value opts))
(defun get-receipt (name session receipt-id) (wiregrid_api:get_receipt name session receipt-id))

;; Bounded read-only query surface.
(defun session (name session-id) (wiregrid_api:session name session-id))
(defun user-sessions (name user-id) (wiregrid_api:user_sessions name user-id))
(defun user-sessions (name user-id limit) (wiregrid_api:user_sessions name user-id limit))
(defun session-state (name session-id) (wiregrid_api:session_state name session-id))
(defun session-state (name session-id limit) (wiregrid_api:session_state name session-id limit))
(defun topic-info (name topic) (wiregrid_api:topic_info name topic))
(defun topic-info (name topic limit) (wiregrid_api:topic_info name topic limit))
(defun room-info (name room) (wiregrid_api:room_info name room))
(defun room-info (name room limit) (wiregrid_api:room_info name room limit))
(defun user-info (name user-id) (wiregrid_api:user_info name user-id))
(defun user-info (name user-id limit) (wiregrid_api:user_info name user-id limit))
(defun subscriptions (name session-id) (wiregrid_api:subscriptions name session-id))
(defun subscriptions (name session-id limit) (wiregrid_api:subscriptions name session-id limit))
(defun topic-sessions (name topic) (wiregrid_api:topic_sessions name topic))
(defun topic-sessions (name topic limit) (wiregrid_api:topic_sessions name topic limit))
(defun session-rooms (name session-id) (wiregrid_api:session_rooms name session-id))
(defun session-rooms (name session-id limit) (wiregrid_api:session_rooms name session-id limit))
(defun presence-watches (name session-id) (wiregrid_api:presence_watches name session-id))
(defun presence-watches (name session-id limit) (wiregrid_api:presence_watches name session-id limit))
(defun room-member? (name room session-id) (wiregrid_api:room_member name room session-id))
(defun subscribed? (name session-id topic) (wiregrid_api:subscribed name session-id topic))
(defun topic-subscriber-count (name topic) (wiregrid_api:topic_subscriber_count name topic))
(defun room-member-count (name room) (wiregrid_api:room_member_count name room))
(defun presence-watcher-count (name user) (wiregrid_api:presence_watcher_count name user))
(defun user-session-count (name user) (wiregrid_api:user_session_count name user))
(defun limits (name) (wiregrid_api:limits name))
(defun delivery-event (name envelope) (wiregrid_api:delivery_event name envelope))
(defun consume-delivery (name envelope handler) (wiregrid_api:consume_delivery name envelope handler))
(defun consume-many-deliveries (name envelopes handler) (wiregrid_api:consume_many_deliveries name envelopes handler))
(defun consume-ordered-deliveries (name envelopes handler) (wiregrid_api:consume_ordered_deliveries name envelopes handler))
(defun consume-projection (name envelopes accumulator reducer commit) (wiregrid_api:consume_projection name envelopes accumulator reducer commit))
(defun request-session (name requester target event) (wiregrid_api:request_session name requester target event))
(defun request-session (name requester target event opts) (wiregrid_api:request_session name requester target event opts))
(defun reply (name replier request-envelope event) (wiregrid_api:reply name replier request-envelope event))
(defun reply (name replier request-envelope event opts) (wiregrid_api:reply name replier request-envelope event opts))
(defun request-context (envelope) (wiregrid_api:request_context envelope))
(defun transport-audience (instance) (wiregrid_api:transport_audience instance))
(defun issue-transport-token (subject keys) (wiregrid_api:issue_transport_token subject keys))
(defun issue-transport-token (subject keys opts) (wiregrid_api:issue_transport_token subject keys opts))
(defun verify-transport-token (token keys) (wiregrid_api:verify_transport_token token keys))
(defun verify-transport-token (token keys opts) (wiregrid_api:verify_transport_token token keys opts))

;; Generic primitives and adapters.
(defun rate-limit (name bucket key limit window-ms) (wiregrid_api:rate_limit name bucket key limit window-ms))
(defun rate-limit (name bucket key limit window-ms opts) (wiregrid_api:rate_limit name bucket key limit window-ms opts))
(defun webhook (name url body) (wiregrid_api:webhook name url body))
(defun webhook (name url body opts) (wiregrid_api:webhook name url body opts))
(defun replay-session (name session stream) (wiregrid_api:replay_session name session stream))
(defun replay-session (name session stream opts) (wiregrid_api:replay_session name session stream opts))
(defun storage-bootstrap (name) (wiregrid_api:storage_bootstrap name))
(defun storage-health (name) (wiregrid_api:storage_health name))
(defun storage-append (name stream id event) (wiregrid_api:storage_append name stream id event))
(defun storage-append (name stream id event meta) (wiregrid_api:storage_append name stream id event meta))
(defun storage-get (name stream id) (wiregrid_api:storage_get name stream id))
(defun storage-page (name stream) (wiregrid_api:storage_page name stream))
(defun storage-page (name stream cursor limit) (wiregrid_api:storage_page name stream cursor limit))
(defun read-history (name session stream) (wiregrid_api:read_history name session stream))
(defun read-history (name session stream cursor) (wiregrid_api:read_history name session stream cursor))
(defun read-history (name session stream cursor limit) (wiregrid_api:read_history name session stream cursor limit))
(defun storage-delete (name stream id) (wiregrid_api:storage_delete name stream id))
(defun storage-prune (name stream before-ms) (wiregrid_api:storage_prune name stream before-ms))
(defun storage-prune (name stream before-ms limit) (wiregrid_api:storage_prune name stream before-ms limit))
(defun cache-get (name key) (wiregrid_api:cache_get name key))
(defun cache-put (name key value) (wiregrid_api:cache_put name key value))
(defun cache-put (name key value ttl) (wiregrid_api:cache_put name key value ttl))
(defun cache-delete (name key) (wiregrid_api:cache_delete name key))
(defun cache-incr (name key) (wiregrid_api:cache_incr name key))
(defun cache-incr (name key delta) (wiregrid_api:cache_incr name key delta))
(defun cache-incr (name key delta ttl) (wiregrid_api:cache_incr name key delta ttl))
(defun cache-health (name) (wiregrid_api:cache_health name))

;; Operations.
(defun health (name) (wiregrid_api:health name))
(defun readiness (name) (wiregrid_api:readiness name))
(defun readiness-report (name) (wiregrid_api:readiness_report name))
(defun deployment-report (name) (wiregrid_api:deployment_report name))
(defun ready? (name) (wiregrid_api:ready name))
(defun liveness (name) (wiregrid_api:liveness name))
(defun stats (name) (wiregrid_api:stats name))
(defun pressure (name) (wiregrid_api:pressure name))
(defun prometheus-metrics (name) (wiregrid_api:prometheus_metrics name))
(defun drain (name) (wiregrid_api:drain name))
(defun undrain (name) (wiregrid_api:undrain name))
(defun await-idle (name) (wiregrid_api:await_idle name))
(defun await-idle (name timeout-ms) (wiregrid_api:await_idle name timeout-ms))
(defun graceful-shutdown (name) (wiregrid_api:graceful_shutdown name))
(defun graceful-shutdown (name timeout-ms) (wiregrid_api:graceful_shutdown name timeout-ms))
